mysite/urls.py
from django.urls import include, path
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    path('school/', include('school.urls')),
    path('admin/', admin.site.urls),
    path('',  RedirectView.as_view(url='/school/')),
]

school/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views

app_name = 'school'

urlpatterns = [
    path('subjects/', views.index, name='index'),
    path('subjects/create/', views.create, name='create'),
    url(r'^assignment/$', views.assign, name='urlname')
]

school/models.py
from django.db import models

# Create your models here.

class Subject(models.Model):
    name = models.CharField(max_length=200)

class Assignments(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    assign = models.CharField(max_length=50)

school/forms.py
from django import forms

from .models import Subject

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ('name',)

school/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Subject, Assignments
from .forms import SubjectForm


# Create your views here.
def index(request):
    subjects = Subject.objects.all()
    form = SubjectForm()
    context = {'subjects': subjects, 'form': form, }
    return render(request, 'index.html', context)
    
def create(request):
    form = SubjectForm(request.POST)
    form.save(commit=True)
    return HttpResponseRedirect(reverse('school:index'))


def assign(request):
    name = request.GET['name']
    # post = Post.objects.get(slug=slug)
    assignments = Assignments.objects.filter(subject=name)
    context = {'assigns': assignments, 'name':name }
    return render(request, 'assign.html', context)

school/templates/assign.html
{% extends 'base.html' %}

{% block content %}
    <h1>Assignment List</h1>
    <table class="table table-striped todo-table">
        <thead>
            <!-- <th>{{ name }}</th><th>&nbsp;</th> -->
        </thead>

        <tbody>
            {% for subject in assigns %}
                <tr>
                    <!-- Subject Name -->
                    <td>
                        <div>{{subject.subject}} : {{ subject.assign }}</div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
{% endblock %}

school/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Todo List</title>
        <!-- CSS And JavaScript -->
        <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
        <link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">
        <link rel="stylesheet" href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">
        <link rel="stylesheet" href="{% static 'css/todo.css' %}">
    </head>
    <body>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

school/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Subject List</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'school:create' %}" method="post">
        {% csrf_token %}
        <!-- Subject Name -->
        <div class="form-group">
            <label for="subject" class="col-sm-3 control-label">Subject</label>
            <div class="col-sm-6">
                {{ form.name }}
            </div>
        </div>

        <!-- Add Subject Button -->
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-6">
                <button type="submit" class="btn btn-default">
                    <i class="fa fa-plus"></i> Add Subject
                </button>
            </div>
        </div>

    </form>
    

    <!-- Current Subjects -->
    <h2>Current Subjects</h2>
    <table class="table table-striped todo-table">
        <thead>
            <th>Subjects</th><th>&nbsp;</th>
        </thead>

        <tbody>
            {% for subject in subjects %}
                <tr>
                    <!-- Subject Name -->
                    <td>
                        <div>{{ subject.name }}</div>
                    </td>
                    <td>
                        <button>View</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
{% endblock %}